name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go environment
      uses: actions/setup-go@v4.1.0
      with:
        go-version: 1.18

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.8.1
      with:
        node-version: 12

    - name: Setup Go Project
      run: go mod init github.com/aleforge/assetto-server-manager

    - name: Run Clean
      run: make clean

    - name: Run Assets
      run: make assets

    - name: Run embed assests
      run: make asset-embed

    - name: Run build
      run: make build
